import React, { useMemo, useState } from "react";

const baseNiches = [
  "Animal Coloring Book","Minimalist Line Art","Ocean Life Coloring","Cozy Lifestyle Coloring","Cottagecore Aesthetic Coloring","Dark Academia Coloring Book","Cute Horror Chibi Book","Sleep Therapy Coloring Pages","Mindfulness Mandala Book","Botanical Coloring","Fairy Tale Coloring","Urban Sketch Coloring","Motivational Quotes Coloring","Fashion Coloring Book","Cute Animals Coloring","Fantasy Creatures Coloring","Kawaii Coloring Book","Nature Coloring","Anxiety Relief Coloring Book","ADHD Focus Workbook"
];

function getDaySeed(){ const d = new Date(); return `${d.getFullYear()}-${d.getMonth()}-${d.getDate()}`; }
function hashString(str){ let h=0; for(let i=0;i<str.length;i++) h=(h*31+str.charCodeAt(i))%100000; return h; }
function rand(seed,i){ const x=Math.sin(seed*999+i*1234)*10000; return x-Math.floor(x); }
function makeNiches(force=0){ const seed=hashString(getDaySeed()+force); return baseNiches.map((name,i)=>{ const trend=Math.floor(rand(seed,i+10)*100); const competition=rand(seed,i+20)>0.55?"Low":"Medium"; const score=Math.floor(rand(seed,i)*5+5); let opportunity=score+(competition==="Low"?2:0)+(trend>70?2:0); const trendType=trend>70?"Trending":trend>40?"Stable":"Evergreen"; let decision="⚠️ Skip"; if(competition==="Low"&&trend>50) decision="🔥 Publish Now"; else if(competition==="Low") decision="✅ Good Opportunity"; else if(trend>70) decision="⚡ Fast Trend"; return {name,trend,competition,score,opportunity,trendType,decision}; }).sort((a,b)=>b.opportunity-a.opportunity); }
function subNiches(niche){ return ["Mandala therapy pages","Stress relief patterns","Focus training workbook","Mindfulness flow","Aesthetic variations","Daily relaxation","Beginner friendly","Advanced detail pages"].slice(0,3); }
function keywords(niche){ return [`${niche.toLowerCase()} aesthetic pages`,`cozy vintage nature scenes`,`relaxing farmhouse vibes`,`anti stress creative therapy`,`slow living art activity`,`mindfulness calm drawing`,`rustic floral designs`]; }
function prompts(niche){ return Array.from({length:30},(_,i)=>`${niche} scene ${i+1}, black and white coloring page, clean bold lines, no shading, white background, printable KDP interior`); }
function bookPack(niche){ return { niche, title:`${niche}: Stress Relief Coloring Book for Adults`, subtitle:"Relaxing Designs for Mindfulness and Creativity", keywords:keywords(niche), cover:`${niche} cover design, bold typography, eye-catching composition, high contrast, clean modern KDP book cover, professional bestselling style`, description:`✨ Discover the Magic of ${niche}! ✨\n\nUnwind, relax, and express your creativity with this beautifully designed coloring book.\n\n✔ Stress-relieving designs\n✔ Perfect for mindfulness and relaxation\n✔ Great gift idea\n✔ High-quality pages\n\nStart your creative journey today.`, prompts:prompts(niche)}; }
function researchLinks(niche){ const q=encodeURIComponent(niche); return {amazon:`https://www.amazon.com/s?k=${q}`,trends:`https://trends.google.com/trends/explore?q=${q}`,etsy:`https://www.etsy.com/search?q=${q}`,pinterest:`https://www.pinterest.com/search/pins/?q=${q}`,google:`https://www.google.com/search?q=${q}+coloring+book+amazon+kdp`}; }
function Checklist(){ return <div className="bg-slate-900 p-5 rounded mb-6 border border-slate-700 shadow-lg"><h2 className="text-xl font-bold mb-2">🧠 KDP Dashboard</h2><ul className="text-sm space-y-1 list-disc ml-5"><li>Daily 20 Niches Engine ACTIVE</li><li>Auto Refresh every day</li><li>Sub-niche generator ON</li><li>Search system enabled</li><li>Cover generator added</li><li>Description generator added</li></ul></div> }
function Badge({d}){ const c=d.includes("Publish")?"bg-green-700":d.includes("Good")?"bg-blue-700":d.includes("Fast")?"bg-yellow-700":"bg-red-700"; return <span className={`${c} px-2 py-1 rounded text-xs font-bold`}>{d}</span> }

export default function App(){
  const [tab,setTab]=useState("overview"),[refresh,setRefresh]=useState(0),[only,setOnly]=useState(false),[sub,setSub]=useState({}),[book,setBook]=useState(null),[factory,setFactory]=useState(null),[research,setResearch]=useState(null),[copied,setCopied]=useState("");
  const niches=useMemo(()=>makeNiches(refresh),[refresh]); const visible=only?niches.filter(n=>n.decision.includes("Publish")||n.decision.includes("Good")):niches;
  const copy=(text,key)=>{navigator.clipboard.writeText(text); setCopied(key); setTimeout(()=>setCopied(""),1500)};
  const makeBook=(n)=>{setBook(bookPack(n));setTab("book")}; const makeFactory=(n)=>{setFactory(bookPack(n));setTab("factory")};
  return <div className="min-h-screen bg-black text-white p-6"><div className="max-w-7xl mx-auto"><h1 className="text-2xl font-bold mb-4">KDP Dashboard V7 🚀</h1><Checklist />
  <div className="bg-slate-900 p-4 rounded mb-6 border border-slate-700"><div className="flex flex-wrap gap-2"><button onClick={()=>setRefresh(r=>r+1)} className="bg-purple-600 hover:bg-purple-500 px-3 py-2 rounded">🔄 Refresh Niches</button><button onClick={()=>setOnly(v=>!v)} className="bg-green-600 hover:bg-green-500 px-3 py-2 rounded">🔥 {only?"Show All Niches":"Only Winning Niches"}</button></div><p className="text-xs text-slate-400 mt-3">يعرض النيتشات التي تستحق التجربة بناءً على Competition + Trend + Opportunity.</p></div>
  <div className="flex flex-wrap gap-2 mb-4"><button onClick={()=>setTab("overview")} className="bg-slate-800 hover:bg-slate-700 px-4 py-2 rounded">Niche Overview</button><button onClick={()=>setTab("deep")} className="bg-slate-800 hover:bg-slate-700 px-4 py-2 rounded">Deep Dive</button><button onClick={()=>setTab("research")} className="bg-slate-800 hover:bg-slate-700 px-4 py-2 rounded">🔍 Smart Research</button><button onClick={()=>setTab("book")} className="bg-slate-800 hover:bg-slate-700 px-4 py-2 rounded">Book Generator</button><button onClick={()=>setTab("factory")} className="bg-slate-800 hover:bg-slate-700 px-4 py-2 rounded">🤖 Auto Book Factory</button></div>
  {tab==="overview"&&<div className="grid md:grid-cols-2 gap-3">{visible.map((n,i)=><div key={i} className="bg-slate-900 p-4 rounded border border-slate-700"><div className="flex justify-between"><h3 className="font-bold">{n.name}</h3><Badge d={n.decision}/></div><p>🎯 Score: {n.score}/10</p><p>🔥 Trend: {n.trend}%</p><p>⚔ Competition: {n.competition}</p><p>💰 Opportunity: {n.opportunity}/10</p><div className="flex flex-wrap gap-2 mt-3"><button className="bg-blue-600 px-2 py-1 rounded text-xs" onClick={()=>makeBook(n.name)}>Generate Book</button><button className="bg-green-600 px-2 py-1 rounded text-xs" onClick={()=>setSub(p=>({...p,[i]:p[i]?null:subNiches(n.name)}))}>Sub Niches</button><button className="bg-cyan-600 px-2 py-1 rounded text-xs" onClick={()=>{setResearch(n.name);setTab("research")}}>🔍 Research</button><button className="bg-pink-600 px-2 py-1 rounded text-xs" onClick={()=>makeFactory(n.name)}>🤖 Factory</button></div>{sub[i]&&<ul className="mt-3 text-sm list-disc ml-5 space-y-2">{sub[i].map((s,k)=><li key={k} className="flex justify-between gap-2"><span>{s}</span><div className="flex gap-2"><button className="bg-yellow-600 px-2 py-1 rounded text-xs" onClick={()=>makeBook(`${n.name} - ${s}`)}>Generate</button><button className="bg-cyan-600 px-2 py-1 rounded text-xs" onClick={()=>{setResearch(`${n.name} - ${s}`);setTab("research")}}>Research</button><button className="bg-pink-600 px-2 py-1 rounded text-xs" onClick={()=>makeFactory(`${n.name} - ${s}`)}>Factory</button></div></li>)}</ul>}</div>)}</div>}
  {tab==="deep"&&<div className="grid md:grid-cols-2 gap-4">{visible.slice(0,10).map((n,i)=><div key={i} className="bg-slate-900 p-4 rounded border border-slate-700"><div className="flex justify-between"><h3 className="font-bold">{n.name}</h3><Badge d={n.decision}/></div><p>🎯 Opportunity Score: {n.opportunity}/10</p><p>📈 Trend: {n.trend}% ({n.trendType})</p><p>⚔ Competition: {n.competition}</p><p className="font-bold mt-3">💡 Strategy:</p><ul className="text-sm list-disc ml-5"><li>{n.competition==="Low"?"Better chance to rank quickly.":"Use a narrow sub-niche angle to compete."}</li><li>{n.trendType==="Trending"?"Publish fast because the trend is hot.":"Build long-term listing quality."}</li></ul></div>)}</div>}
  {tab==="research"&&(!research?<div className="bg-slate-900 p-4 rounded border border-slate-700">اختر نيتش ثم اضغط Research.</div>:<div className="bg-slate-900 p-4 rounded border border-slate-700"><h2 className="font-bold mb-3">🔍 Smart Research Dashboard</h2><p><b>Selected niche:</b> {research}</p>{Object.entries(researchLinks(research)).map(([k,u])=><div key={k} className="bg-black p-2 rounded border border-slate-800 mt-2"><a className="bg-cyan-700 px-3 py-1 rounded text-xs" href={u} target="_blank" rel="noreferrer">Open {k}</a><button className="bg-slate-700 px-2 py-1 rounded text-xs ml-2" onClick={()=>copy(u,k)}>Copy Link</button><div className="text-xs text-slate-500 break-all mt-1">{u}</div></div>)}</div>)}
  {tab==="book"&&(!book?<div className="bg-slate-900 p-4 rounded border border-slate-700">اختر نيتش ثم اضغط Generate Book.</div>:<div className="bg-slate-900 p-4 rounded border border-slate-700"><h2 className="font-bold mb-3">Book Pack</h2><p><b>Niche:</b> {book.niche}</p><p className="mt-3"><b>Title:</b> {book.title}</p><button className="bg-slate-700 px-2 py-1 rounded text-xs" onClick={()=>copy(book.title,"title")}>{copied==="title"?"Copied!":"Copy Title"}</button><p className="mt-3"><b>Subtitle:</b> {book.subtitle}</p><p className="mt-3"><b>Keywords:</b></p><ul className="text-sm list-disc ml-5">{book.keywords.map((k,i)=><li key={i}>{k}</li>)}</ul><button className="bg-slate-700 px-2 py-1 rounded text-xs" onClick={()=>copy(book.keywords.join(", "),"keywords")}>{copied==="keywords"?"Copied!":"Copy Keywords"}</button><p className="mt-3"><b>Cover Prompt:</b></p><p className="text-sm">{book.cover}</p><p className="mt-3"><b>Description:</b></p><p className="text-sm whitespace-pre-line">{book.description}</p><p className="mt-3"><b>30 Prompts:</b></p><div className="max-h-48 overflow-auto text-sm bg-black p-3 rounded border border-slate-800">{book.prompts.map((p,i)=><div key={i}>{i+1}. {p}</div>)}</div></div>)}
  {tab==="factory"&&(!factory?<div className="bg-slate-900 p-4 rounded border border-slate-700">اختر نيتش ثم اضغط 🤖 Factory.</div>:<div className="bg-slate-900 p-4 rounded border border-slate-700"><h2 className="font-bold mb-3">🤖 Auto Book Factory</h2><p><b>Niche:</b> {factory.niche}</p><div className="grid md:grid-cols-3 gap-3 mt-4"><div className="bg-black p-3 rounded border border-slate-800"><h3 className="font-bold">1) الصور</h3><p className="text-sm text-slate-300">Image prompts ready.</p><button onClick={()=>copy(factory.prompts.join("\n"),"fp")} className="mt-2 bg-slate-700 px-2 py-1 rounded text-xs">Copy Image Prompts</button></div><div className="bg-black p-3 rounded border border-slate-800"><h3 className="font-bold">2) الغلاف</h3><p className="text-xs mt-2">{factory.cover}</p></div><div className="bg-black p-3 rounded border border-slate-800"><h3 className="font-bold">3) PDF جاهز</h3><p className="text-sm text-slate-300">Use Canva or PowerPoint to export PDF.</p></div></div></div>)}
  </div></div>}
